spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 7428@0203
    url: jdbc:mysql://localhost:3306/db_assign_online?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&allowMutiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  type-aliases-package: com.vere.assign_online.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: Bearer

qny:
  accessKey: zhVJcLSYPXdI0l9GwNcYTHEz-5KYh_GMzNe3XQxs
  secretKey: eJPedoV_bctCRHEGw2oRaLh04KMyuGN6HuIQorZt
  bucket: haihaihai
  domain: http://rcms9b848.hd-bkt.clouddn.com/assign_online/

